// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3Ok_3OC3RSXE3y4TLp16T4C1Do8YMmC4',
    appId: '1:808546057934:web:88e29d147c6d3224dada9f',
    messagingSenderId: '808546057934',
    projectId: 'gina-app-4',
    authDomain: 'gina-app-4.firebaseapp.com',
    storageBucket: 'gina-app-4.appspot.com',
    measurementId: 'G-0NQJV069N5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGaaYbQY22NiTCqst5KlOvAGbieoZ7Pek',
    appId: '1:808546057934:android:d57a9a9ad94982d1dada9f',
    messagingSenderId: '808546057934',
    projectId: 'gina-app-4',
    storageBucket: 'gina-app-4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMUZfwiJ8EBc97ZbcKzZPymUlvwJ_Fsz8',
    appId: '1:808546057934:ios:cc5d6aeb9bbba1f2dada9f',
    messagingSenderId: '808546057934',
    projectId: 'gina-app-4',
    storageBucket: 'gina-app-4.appspot.com',
    iosBundleId: 'com.example.ginaApp4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMUZfwiJ8EBc97ZbcKzZPymUlvwJ_Fsz8',
    appId: '1:808546057934:ios:cc5d6aeb9bbba1f2dada9f',
    messagingSenderId: '808546057934',
    projectId: 'gina-app-4',
    storageBucket: 'gina-app-4.appspot.com',
    iosBundleId: 'com.example.ginaApp4',
  );
}
