name: gina_app_4
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  easy_date_timeline: ^1.0.2
  equatable: ^2.0.5
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  firebase_core_platform_interface: ^5.0.0
  firebase_database: ^10.3.6
  firebase_storage: ^11.6.6
  cloud_firestore: ^4.15.5
  flutter_bloc: ^8.1.3
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.12
  gap: ^3.0.1
  geodesy: ^0.10.2
  geolocator: ^10.1.0
  get_it: ^7.6.4
  google_maps_flutter: ^2.5.3
  google_places_for_flutter: ^1.0.1
  image_picker: ^1.0.7
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  syncfusion_flutter_datepicker: ^24.1.45
  timeago: ^3.6.1
  uuid: ^4.3.3
  web: ^0.4.0
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  dotted_border: ^2.1.0
  lottie: ^3.0.0
  flutter_svg: ^2.0.9
  flutter_launcher_icons: ^0.13.1
  loading_indicator: ^3.1.1
  splash_view: ^2.0.1
  icons_plus: ^5.0.0
  crystal_navigation_bar: ^1.0.0
  wave: ^0.2.2
  shrink_sidemenu: ^2.0.0+2-null-safety
  badges: ^3.1.2
  swipeable_card_stack: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/patient_features/
    - assets/images/patient_features/doctor_office_address/
    - assets/images/patient_features/profile/
    - assets/images/patient_features/home/
  
  fonts:
    - family: SF UI Display
      fonts:
        - asset: assets/fonts/sf ui display/sf-ui-display-black.otf
        - asset: assets/fonts/sf ui display/sf-ui-display-bold.otf
        - asset: assets/fonts/sf ui display/sf-ui-display-heavy.otf
        - asset: assets/fonts/sf ui display/sf-ui-display-light.otf
        - asset: assets/fonts/sf ui display/sf-ui-display-medium.otf
        - asset: assets/fonts/sf ui display/sf-ui-display-semibold.otf
        - asset: assets/fonts/sf ui display/sf-ui-display-thin.otf
        - asset: assets/fonts/sf ui display/sf-ui-display-ultralight.otf

    - family: Cormorant Upright
      fonts:
        - asset: assets/fonts/Cormorant Upright/CormorantUpright-Bold.ttf
        - asset: assets/fonts/Cormorant Upright/CormorantUpright-Light.ttf
        - asset: assets/fonts/Cormorant Upright/CormorantUpright-Medium.ttf
        - asset: assets/fonts/Cormorant Upright/CormorantUpright-Regular.ttf
        - asset: assets/fonts/Cormorant Upright/CormorantUpright-SemiBold.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/gina_favicon.png"