name: gina_app_4
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  about: ^2.2.0
  badges: ^3.1.2
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.15.5
  collection: ^1.18.0
  crystal_navigation_bar: ^1.0.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dotted_border: ^2.1.0
  easy_date_timeline: ^1.0.2
  equatable: ^2.0.5
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  firebase_core_platform_interface: ^5.0.0
  firebase_database: ^10.3.6
  firebase_storage: ^11.6.6
  flutter:
    sdk: flutter
  flutter_animated_icons: any
  flutter_bloc: ^8.1.3
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.12
  flutter_custom_tab_bar: ^1.2.1
  flutter_expandable_table: ^2.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.9
  flutter_swiper_view: ^1.1.8
  flutter_web_data_table: ^1.0.0
  gap: ^3.0.1
  geocoding: ^3.0.0
  geodesy: ^0.10.2
  geolocator: ^10.1.0
  get_it: ^7.6.4
  glassmorphism: ^3.0.0
  google_maps_flutter: ^2.5.3
  google_places_for_flutter: ^1.0.1
  icons_plus: ^5.0.0
  image_picker: ^1.0.7
  intl: ^0.19.0
  loading_indicator: ^3.1.1
  lottie: ^3.0.0
  menstrual_cycle_widget: ^1.1.1
  shared_preferences: ^2.2.2
  simple_progress_indicators: ^0.2.0
  skeletonizer: ^1.4.2
  splash_view: ^2.0.1
  syncfusion_flutter_datepicker: ^24.1.45
  table_calendar: ^3.1.2
  timeago: ^3.6.1
  uuid: ^4.3.3
  wave: ^0.2.2
  web: ^0.4.0

dependency_overrides:
  lottie: ^1.4.3

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/lotties/
    - assets/images/patient_features/
    - assets/images/patient_features/doctor_office_address/
    - assets/images/patient_features/profile/
    - assets/images/patient_features/home/
    - assets/images/patient_features/forums/
    - assets/images/doctor_features/
    - assets/images/doctor_features/home/
    - assets/images/doctor_features/forum_doctor_badges/
    - assets/images/doctor_features/consultation_fee/

  fonts:
    - family: SF UI Display
      fonts:
        - asset: assets/fonts/sf ui display/sf-ui-display-black.otf
        - asset: assets/fonts/sf ui display/sf-ui-display-bold.otf
        - asset: assets/fonts/sf ui display/sf-ui-display-heavy.otf
        - asset: assets/fonts/sf ui display/sf-ui-display-light.otf
        - asset: assets/fonts/sf ui display/sf-ui-display-medium.otf
        - asset: assets/fonts/sf ui display/sf-ui-display-semibold.otf
        - asset: assets/fonts/sf ui display/sf-ui-display-thin.otf
        - asset: assets/fonts/sf ui display/sf-ui-display-ultralight.otf

    - family: Cormorant Upright
      fonts:
        - asset: assets/fonts/Cormorant Upright/CormorantUpright-Bold.ttf
        - asset: assets/fonts/Cormorant Upright/CormorantUpright-Light.ttf
        - asset: assets/fonts/Cormorant Upright/CormorantUpright-Medium.ttf
        - asset: assets/fonts/Cormorant Upright/CormorantUpright-Regular.ttf
        - asset: assets/fonts/Cormorant Upright/CormorantUpright-SemiBold.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/gina_favicon.png"